language: php

php:
  - 7.3
  - 7.2
  - 7.1
  - 7
  - hhvm-3.18
  - nightly

matrix:
  allow_failures:
    - php: nightly

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - composer test
